#!/usr/bin/env Rscript

library('getopt')

spec = matrix(c(
  'sample', 's', 1, "integer", "sample size for each iteration.",
  'iter', 'i', 1,   "integer", "number of iterations.",
  'host', 'r', 1,   "character", "IP address of redis server.",
  'port', 'p', 1,   "character", "port of redis server, default is 6379",
  'type', 't', 1,   "character", "pert_type, either `trt_sh` (default) or `trt_oe`",
  'help', 'h', 0, "logical", "print usage"
), byrow=TRUE, ncol=5)
opt = getopt(spec)

if ( !is.null(opt$help) ) {
  cat(getopt(spec, usage=TRUE))
  q(status=1)
}

if ( is.null(opt$port    ) ) { opt$port      = 6379      }
if ( is.null(opt$type    ) ) { opt$type      = "trt_sh"}
if ( is.null(opt$host    ) ) { stop("--host argument is required.")      }
if ( is.null(opt$sample ) ) { stop("--sample argument is required.")}
if ( is.null(opt$iter ) ) { stop("--iter argument is required.")}
if ( is.null(opt$outfile) ) { opt$outfile = paste0("gene_", opt$type, "_", opt$sample, "_pdf.rds")}

cmd <- paste0("qsub -v HOST=", opt$host, 
              ",PORT=", opt$port,
              ",SAMPLE=", opt$sample,
              ",ITER=", opt$iter,
              ",TYPE=", opt$type, 
              " lib/perm_genes.pbs")

system(cmd)